version: '3.8'

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretword
      POSTGRES_DB: postgres
    volumes:
      - blog:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogApp_container
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:mysecretword@postgres:5432/postgres
      REDIS_URL: redis://redis:6379

volumes:
  blog:
